stages:
  - publish

publish:
  stage: publish
  image: ghcr.io/cirruslabs/android-sdk:34
  rules:
    - if: '$CI_COMMIT_TAG =~ /^v.*/'
    - if: '$CI_PIPELINE_SOURCE == "web"'
  script:
    - chmod +x ./gradlew
    - test -n "$MAVEN_CENTRAL_USERNAME"
    - test -n "$MAVEN_CENTRAL_PASSWORD"
    - test -n "$GPG_PRIVATE_KEY"
    - ./gradlew --no-daemon :core:publishToMavenCentral :sdk:publishToMavenCentral :pangle:publishToMavenCentral :ylh:publishToMavenCentral :noah:publishToMavenCentral :sdk-tools:publishToMavenCentral
