org.gradle.jvmargs=-Xmx2g -Dfile.encoding=UTF-8
android.useAndroidX=true
android.enableJetifier=true
kotlin.code.style=official
android.nonTransitiveRClass=true
LAMPS_VERSION=0.0.14
useLocalLamps=true
# Publish destination: maven (default) or mavenCentral.
LAMPS_PUBLISH_TARGET=maven

# Third-party dependency versions.
PANGLE_ADS_SDK_PRO_VERSION=7.6.1.2_3
PANGLE_ADS_SDK_TOOLS_VERSION=7.6.4.2_3
NOAH_VENDOR_VERSION=15.1.4002_3
GDT_TOOLS_VERSION=2.4
GDT_UNION_VERSION=4.690.1560
